export default function accessToken(token = useCookie('token').value || null) {
  const savedToken = useCookie('token')
  savedToken.value = token // Set Token to the cookie ...
  return savedToken.value || null // Return the current cookie value ...
}
